const EVENT_CATEGORIES = [
  { value: 'lecture', label: '讲座', description: '讲座、报告、论坛、分享会、学术科研活动' },
  { value: 'competition', label: '竞赛', description: '竞赛、比赛、挑战、黑客松、路演和成果展示' },
  { value: 'volunteer', label: '志愿', description: '志愿服务、公益实践、社会实践、社区服务' },
  { value: 'recruitment', label: '招新/职业', description: '招募、招新、招聘、实习、职业发展和组织纳新' },
  { value: 'culture_sports', label: '文体', description: '文化、艺术、美育、体育、演出、展览和放映' },
  { value: 'exchange', label: '交流', description: '国际交流、校友交流、企业交流、留学交换和访学' },
  { value: 'other', label: '校园活动', description: '无法稳定归入以上大类的其他校园活动' },
];

const EVENT_CATEGORY_ALIASES = {
  lecture: [
    'academic',
    'research',
    'talk',
    'academic_research',
    '学术科研',
    '学术讲座',
    '学术报告',
    '讲座',
    '报告',
    '论坛',
    '学术',
    '科研',
    '分享会',
    '宣讲会',
    '论文分享',
    '科研训练',
    '读书会',
    '沙龙',
    '会议',
  ],
  competition: [
    'competition',
    'contest',
    'hackathon',
    'competition_project',
    '竞赛项目',
    '竞赛',
    '比赛',
    '挑战',
    '挑战赛',
    '挑战杯',
    '黑客松',
    '训练营',
    '路演',
    '成果展示',
    '成果展',
  ],
  volunteer: [
    'volunteer',
    'service',
    'public_service',
    '公益实践',
    '志愿服务',
    '志愿活动',
    '志愿',
    '公益',
    '社会实践',
    '社区服务',
    '支教',
    '助老',
    '服务日',
  ],
  recruitment: [
    'recruitment',
    'career',
    'club',
    'career_development',
    '职业发展',
    'club_organization',
    '社团组织',
    '招募',
    '项目招募',
    '团队招募',
    '社团招新',
    '学生组织招新',
    '部门招新',
    '招新',
    '招聘',
    '实习招聘',
    '实习',
    '就业',
    '职业',
    '简历',
    '面试',
    'offer',
    '学生会',
    '研究生会',
  ],
  culture_sports: [
    'culture',
    'sports',
    'art',
    '文体美育',
    '文体活动',
    '文体',
    '美育',
    '演出',
    '展览',
    '体育',
    '艺术',
    '文化节',
    '音乐会',
    '音乐',
    '电影放映',
    '电影',
    '运动',
  ],
  exchange: [
    'exchange',
    'international',
    'international_exchange',
    '国际交流',
    '交流',
    '校友交流',
    '企业交流',
    '跨校交流',
    '留学',
    '交换',
    '访学',
    '海外',
    '外事',
    '国际',
    '校友',
  ],
  other: [
    'other',
    'tech_innovation',
    '技术创新',
    'campus_life',
    '校园生活',
    '其他',
    '班团活动',
    '校园服务',
    '生活服务',
    '市集',
  ],
};

const EVENT_CATEGORY_LABELS = EVENT_CATEGORIES.reduce((accumulator, item) => {
  accumulator[item.value] = item.label;
  return accumulator;
}, {});

const EVENT_AUDIENCE_GROUPS = [
  {
    group: '学习阶段',
    items: [
      '本科生',
      '研究生',
      '硕士生',
      '博士生',
      '新生',
    ],
  },
  {
    group: '学园与特殊培养单位',
    items: [
      '全校',
      '求是学院',
      '丹青学园',
      '云峰学园',
      '蓝田学园',
      '竺可桢学院',
      '工程师学院',
      '国际联合学院',
      '国际教育学院',
    ],
  },
  {
    group: '人文与社科',
    items: [
      '文学院',
      '历史学院',
      '哲学学院',
      '外国语学院',
      '传媒与国际文化学院',
      '艺术与考古学院',
      '经济学院',
      '光华法学院',
      '教育学院',
      '管理学院',
      '公共管理学院',
      '马克思主义学院',
    ],
  },
  {
    group: '理学与工学',
    items: [
      '数学科学学院',
      '物理学院',
      '化学系',
      '地球科学学院',
      '心理与行为科学系',
      '机械工程学院',
      '材料科学与工程学院',
      '能源工程学院',
      '电气工程学院',
      '建筑工程学院',
      '化学工程与生物工程学院',
      '海洋学院',
      '航空航天学院',
      '高分子科学与工程学系',
    ],
  },
  {
    group: '信息学部',
    items: [
      '光电科学与工程学院',
      '信息与电子工程学院',
      '控制科学与工程学院',
      '计算机科学与技术学院',
      '软件学院',
      '生物医学工程与仪器科学学院',
      '集成电路学院',
    ],
  },
  {
    group: '农生环与医学',
    items: [
      '生命科学学院',
      '生物系统工程与食品科学学院',
      '环境与资源学院',
      '农业与生物技术学院',
      '动物科学学院',
      '医学院',
      '药学院',
    ],
  },
  {
    group: '中外合作办学',
    items: [
      '浙江大学伊利诺伊大学厄巴纳香槟校区联合学院',
      '浙江大学爱丁堡大学联合学院',
    ],
  },
];

const EVENT_AUDIENCE_OPTIONS = EVENT_AUDIENCE_GROUPS.flatMap(({ items }) => items);

const EVENT_AUDIENCE_ALIASES = [
  '全校',
  '全体师生',
  '全校师生',
  '所有学生',
  '全体学生',
  '本科',
  '本科生',
  '研究生',
  '硕士',
  '硕士生',
  '博士',
  '博士生',
  '新生',
  '大一',
  '大二',
  '大三',
  '大四',
];

const EVENT_CAMPUS_OPTIONS = [
  '紫金港',
  '玉泉',
  '西溪',
  '华家池',
  '之江',
  '舟山',
  '海宁',
  '线上',
  '在线',
  '直播',
];

const EVENT_ALLOWED_EXTRACTION_TAGS = [
  '讲座',
  '志愿活动',
  '竞赛',
  '沙龙',
  '展览',
  '演出',
  '会议',
  '文体活动',
  '招聘',
  '宣讲',
  '学术报告',
  '社会实践',
  '班团活动',
  'AI',
  '新生',
  '综测',
];

module.exports = {
  EVENT_CATEGORIES,
  EVENT_CATEGORY_ALIASES,
  EVENT_CATEGORY_LABELS,
  EVENT_AUDIENCE_GROUPS,
  EVENT_AUDIENCE_OPTIONS,
  EVENT_AUDIENCE_ALIASES,
  EVENT_CAMPUS_OPTIONS,
  EVENT_ALLOWED_EXTRACTION_TAGS,
};
