export const localizedNames = {
    zh: {
        qwen: "通义千问",
        doubao: "豆包",
        modelscope: "魔搭 ModelScope",
        uci: "UCI 数据集",
        coze: "扣子 Coze",
        python: "Python 文档",
        csdiy: "CS 自学指南",
        d2l: "动手学深度学习",
        mooc: "中国大学 MOOC",
        luogu: "洛谷",
        "kaggle-comp": "Kaggle 竞赛",
        tianchi: "天池",
        jiqizhixin: "机器之心",
        qbitai: "量子位",
        juejin: "掘金",
        zdbk: "浙大本科",
        courses: "学在浙大",
        zjulib: "浙大图书馆",
        mirrors: "浙大开源镜像",
        zjucourses: "浙大课程攻略",
    },
    en: {
        qwen: "Qwen",
        doubao: "Doubao",
        modelscope: "ModelScope",
        uci: "UCI Datasets",
        coze: "Coze",
        python: "Python Docs",
        csdiy: "CS DIY",
        d2l: "Dive into Deep Learning",
        mooc: "China University MOOC",
        luogu: "Luogu",
        "kaggle-comp": "Kaggle Competitions",
        tianchi: "Tianchi",
        jiqizhixin: "Synced",
        qbitai: "QbitAI",
        juejin: "Juejin",
        zdbk: "ZJU Undergraduate Portal",
        courses: "Learning at ZJU",
        zjulib: "ZJU Library",
        mirrors: "ZJU Mirrors",
        zjucourses: "ZJU Course Guide",
    },
};
